# Generated by Django 3.2.14 on 2022-07-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220711_1457'),
        ('blog', '0002_delete_addpost'),
    ]

    operations = [
    ]
